
import type { paths } from "../api/v1"; // generated by openapi-typescript
import createClient from "openapi-fetch";

const BASE_URL = "http://192.168.1.182:8080/api"

export const CLIENT = createClient<paths>({ baseUrl: BASE_URL })
