
import type { paths } from "../api/v1"; // generated by openapi-typescript
import createClient from "openapi-fetch";

const IPV4 = "172.20.10.53"
export const BASE_URL = "http://" + IPV4 + ":8080/api"

export const CLIENT = createClient<paths>({ baseUrl: BASE_URL })
